# Generated by Django 3.2 on 2023-01-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDA', '0003_auto_20221230_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
