# Generated by Django 3.2 on 2023-01-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDA', '0004_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['title'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, upload_to='for_albums/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='mymusics',
            name='photo',
            field=models.ImageField(blank=True, upload_to='for_playlists/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='for_playlists/'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(related_name='trackArtist', to='SDA.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='photo',
            field=models.ImageField(blank=True, upload_to='for_tracks/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
