# Generated by Django 3.2 on 2023-02-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDA', '0006_auto_20230212_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='song',
            field=models.FileField(default='', upload_to='for_audiofiles/'),
        ),
    ]
