# Generated by Django 3.2 on 2023-02-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDA', '0007_track_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(default="Someone's album", max_length=500),
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.CharField(default='Information about artist', max_length=500),
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(to='SDA.Artist'),
        ),
    ]
